version: "3.9"

services:
  an_app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/symfony
    volumes:
      - ./symfony:/var/www/symfony
    ports:
      - "8000:8000"
    depends_on:
      - an_postgres_db
      - an_redis
    environment:
      DATABASE_URL: "postgresql://symfony:symfony@an_postgres_db:5432/symfony_db"
      REDIS_URL: redis://an_redis
    command: >
      bash -c "
        composer install --no-interaction &&
        php bin/console doctrine:migrations:migrate --no-interaction &&
        php bin/console messenger:consume async --no-interaction & 
        php -S 0.0.0.0:8000 -t public
      "

  an_postgres_db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: symfony_db
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    ports:
      - "5432:5432"
    volumes:
      - an_pgdata:/var/lib/postgresql/data

  an_redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  an_pgdata:

