version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    working_dir: /var/www/symfony
    volumes:
      - ./symfony:/var/www/symfony
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: "postgresql://symfony:symfony@db:5432/symfony_db"
      REDIS_URL: redis://redis
    command: >
      bash -c "
        composer install --no-interaction &&
        php bin/console doctrine:migrations:migrate --no-interaction &&
        php bin/console messenger:consume async --no-interaction & 
        php -S 0.0.0.0:8000 -t public
      "

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: symfony_db
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis_server
    ports:
      - "6379:6379"

volumes:
  pgdata:

